CREATE TABLE quotes (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL
);

INSERT INTO quotes (text) VALUES
('Successful people are not gifted; they just work hard, then succeed on purpose.'),
('Success isn''t always about greatness. It''s about consistency. Consistent hard work leads to success. Greatness will come.'),
('The only thing standing between you and outrageous success is continuous progress.'),
('I never dreamt of success. I worked for it.'),
('Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don''t quit.'),
('Success is the sum of small efforts, repeated day in and day out.'),
('The most certain way to succeed is always to try just one more time.'),
('Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.'),
('Talent is nothing without persistence.'),
('Persistence is the twin sister of excellence. One is a matter of quality; the other, a matter of time.'),
('A little more persistence, a little more effort and what seemed hopeless failure may turn to glorious success.'),
('Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.'),
('Perseverance is the hard work you do after you get tired of doing the hard work you already did.'),
('It does not matter how slowly you go so long as you do not stop.'),
('Continuous effort—not strength or intelligence—is the key to unlocking our potential.'),
('If you get tired, learn to rest, not to quit.'),
('Perseverance is not a long race; it is many short races one after the other.'),
('Motivation will almost always beat mere talent.'),
('Let me tell you the secret that has led me to my goals: my strength lies solely in my tenacity.'),
('Obstacles can''t stop you. Problems can''t stop you. Most of all, other people can''t stop you. Only you can stop you.'),
('Always do your best. What you plant now, you will harvest later.'),
('Instead of looking at the past, I put myself ahead 20 years and try to look at what I need to do now in order to get there then.'),
('Without hustle, talent will only carry you so far.'),
('Start where you are. Use what you have. Do what you can.'),
('You miss 100% of the shots you don''t take.'),
('Setting goals is the first step in turning the invisible into the visible.'),
('Discipline is choosing between what you want now and what you want most.'),
('Plans are only good intentions unless they immediately degenerate into hard work.'),
('The way to get started is to quit talking and begin doing.'),
('Do not whine. Do not complain. Work harder.'),
('The future depends on what you do today.'),
('Work harder than you think you did yesterday.'),
('All growth depends upon activity. There is no development physically or intellectually without effort, and effort means work.'),
('Nothing ever comes to one, that is worth having, except as a result of hard work.'),
('If you work really hard, and you''re kind, amazing things will happen.'),
('Opportunities are usually disguised as hard work, so most people don''t recognize them.'),
('There will be obstacles. There will be doubters. There will be mistakes. But with hard work, there are no limits.'),
('You''re not obligated to win. You''re obligated to keep trying to do the best you can every day.'),
('I''m a great believer in luck, and I find the harder I work the more I have of it.'),
('I do not know anyone who has got to the top without hard work. That is the recipe. It will not always get you to the top, but should get you pretty near.'),
('When you live for a strong purpose, then hard work isn''t an option. It''s a necessity.'),
('It''s not about money or connections. It''s the willingness to outwork and outlearn everyone.'),
('Always go with the choice that scares you the most, because that''s the one that is going to require the most from you.'),
('Happiness is the real sense of fulfillment that comes from hard work.'),
('This is the real secret of life—to be completely engaged with what you are doing in the here and now. Instead of calling it work, realize it is play.'),
('The only thing that overcomes hard luck is hard work.'),
('A man can make what he wants of himself if he truly believes that he must be ready for hard work and many heartbreaks.');
